import {
  AuditLogEntry,
  GrowthPartner,
  ShopOnboarding,
  KycVerification,
  QrActivation,
  DailyTransaction,
  SettlementRecord,
  Automated15DayCounter,
  MilestonePlusOne,
  DuplicateShop,
  FraudAlert,
  RewardClaim,
  ProductItem,
  VendorDealer,
  InvoiceRecord,
  TaxTdsStatus,
  DispatchRecord,
  VehicleRecord,
  ComplaintAppeal,
} from './types';

export const initialAuditLogs: AuditLogEntry[] = [
  {
    id: 'AUD-8801',
    adminName: 'Aditya Vardhan (Chief Admin)',
    timestamp: '2026-09-28 09:15:22 IST',
    entityType: 'Shop Onboarding',
    entityId: 'SHOP-102',
    entityName: "L'Étoile Hair Lounge (Bandra)",
    fieldChanged: 'Status',
    oldValue: 'pending_review',
    newValue: 'approved',
    changeReason: 'Physical salon interior aesthetics inspection passed high-fashion criteria; 4-chair layout approved.',
  },
  {
    id: 'AUD-8802',
    adminName: 'Radhika Sen (Compliance Officer)',
    timestamp: '2026-09-28 10:42:05 IST',
    entityType: 'KYC Verification',
    entityId: 'KYC-501',
    entityName: 'AURA Luxury Spa (Delhi)',
    fieldChanged: 'KYC Status',
    oldValue: 'pending',
    newValue: 'verified',
    changeReason: 'GSTIN matching MCA registry and active PAN verified with ITD API.',
  },
  {
    id: 'AUD-8803',
    adminName: 'Vikramaditya (Risk & Settlement)',
    timestamp: '2026-09-28 11:30:18 IST',
    entityType: 'Settlement Confirmation',
    entityId: 'SET-901',
    entityName: 'The Obsidian Atelier (Jaipur)',
    fieldChanged: 'Settlement Release',
    oldValue: 'pending',
    newValue: 'confirmed',
    changeReason: 'Escrow 15-day cycle matured; bank UTR generated #HDFC99824108 for net release.',
  },
  {
    id: 'AUD-8804',
    adminName: 'Aditya Vardhan (Chief Admin)',
    timestamp: '2026-09-28 12:10:44 IST',
    entityType: 'QR Terminal',
    entityId: 'QR-004',
    entityName: 'Silk & Ivory Nail Lounge (Bengaluru)',
    fieldChanged: 'QR Status',
    oldValue: 'inactive',
    newValue: 'active',
    changeReason: 'Gold desk stand delivered via BlueDart AWB# 8847192 and tested with UPI live ping.',
  },
];

export const initialGrowthPartners: GrowthPartner[] = [
  {
    id: 'GP-101',
    name: 'Kunal Singhania',
    phone: '+91 98201 44892',
    email: 'kunal.singhania@apexluxury.in',
    region: 'Mumbai & Pune Luxury Hubs',
    salonsReferred: 14,
    commissionRate: '15% of Platform Fee',
    tier: 'Diamond',
    status: 'approved',
    appliedDate: '2026-09-12',
    turnoverContribution: 3850000,
  },
  {
    id: 'GP-102',
    name: 'Meera Rajput',
    phone: '+91 98110 52319',
    email: 'meera.rajput@delhistyle.com',
    region: 'South Delhi & Gurugram High Street',
    salonsReferred: 9,
    commissionRate: '12% of Platform Fee',
    tier: 'Platinum',
    status: 'approved',
    appliedDate: '2026-09-18',
    turnoverContribution: 2420000,
  },
  {
    id: 'GP-103',
    name: 'Farhan Zaidi',
    phone: '+91 97402 18934',
    email: 'farhan.z@bengalurusalons.co',
    region: 'Bengaluru Indiranagar & Koramangala',
    salonsReferred: 4,
    commissionRate: '10% of Platform Fee',
    tier: 'Gold',
    status: 'pending',
    appliedDate: '2026-09-27',
    turnoverContribution: 840000,
  },
  {
    id: 'GP-104',
    name: 'Vikramjit Rathore',
    phone: '+91 94140 82711',
    email: 'vikram.rathore@heritageglam.in',
    region: 'Jaipur & Udaipur Heritage Circuits',
    salonsReferred: 2,
    commissionRate: '10% of Platform Fee',
    tier: 'Gold',
    status: 'pending',
    appliedDate: '2026-09-28',
    turnoverContribution: 320000,
  },
];

export const initialShopsOnboarding: ShopOnboarding[] = [
  {
    id: 'SHOP-101',
    salonName: "L'Étoile Hair Lounge",
    ownerName: 'Master Jean-Jacques & Ananya Roy',
    phone: '+91 98200 99124',
    city: 'Bandra West, Mumbai',
    category: 'Hair Couture & Balayage',
    monthlyTurnover: '₹22,00,000 / month',
    interiorPhoto: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=600',
    status: 'approved',
    submittedDate: '2026-09-20',
    notes: 'Premium gold mirrors, Italian washing stations, 5 VIP styling bays verified.',
  },
  {
    id: 'SHOP-102',
    salonName: 'AURA Luxury Thermal Spa',
    ownerName: 'Aditya Vardhan (Franchisee: Dr. Kabir Sethi)',
    phone: '+91 98111 88392',
    city: 'Vasant Vihar, New Delhi',
    category: 'Thermal Spa & Aesthetics',
    monthlyTurnover: '₹35,00,000 / month',
    interiorPhoto: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600',
    status: 'approved',
    submittedDate: '2026-09-22',
    notes: 'Soundproof obsidian thermal chambers with certified Swiss hydrotherapy pods.',
  },
  {
    id: 'SHOP-103',
    salonName: 'The Obsidian Ink & Piercing Atelier',
    ownerName: 'Sven Lindqvist & Priya Chawla',
    phone: '+91 94140 33819',
    city: 'C-Scheme, Jaipur',
    category: 'Bespoke Ink & Gold Studding',
    monthlyTurnover: '₹14,50,000 / month',
    interiorPhoto: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?auto=format&fit=crop&q=80&w=600',
    status: 'pending_review',
    submittedDate: '2026-09-27',
    notes: 'Sterilization autoclave documentation submitted; waiting for final bio-hazard clearance proof.',
  },
  {
    id: 'SHOP-104',
    salonName: 'Silk & Ivory Couture Nails',
    ownerName: 'Devika Krishnan',
    phone: '+91 97400 66210',
    city: 'UB City, Bengaluru',
    category: 'Couture Nail Art & Spa',
    monthlyTurnover: '₹11,00,000 / month',
    interiorPhoto: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&q=80&w=600',
    status: 'pending_review',
    submittedDate: '2026-09-28',
    notes: 'Japanese LED gel workstations and bespoke champagne bar licensing check pending.',
  },
];

export const initialKycRecords: KycVerification[] = [
  {
    id: 'KYC-501',
    applicantName: "Master Jean-Jacques (L'Étoile)",
    businessName: 'LETOILE LUXURY SALONS LLP',
    panNumber: 'AAFFL8891K',
    gstNumber: '27AAFFL8891K1Z2',
    aadhaarNumber: 'XXXX-XXXX-9142',
    docType: 'GSTIN + PAN',
    status: 'verified',
    verifiedDate: '2026-09-21',
  },
  {
    id: 'KYC-502',
    applicantName: 'Dr. Kabir Sethi (AURA Spa)',
    businessName: 'AURA THERAPEUTICS INDIA PVT LTD',
    panNumber: 'AACCA4491J',
    gstNumber: '07AACCA4491J1ZT',
    aadhaarNumber: 'XXXX-XXXX-1102',
    docType: 'GSTIN + PAN',
    status: 'verified',
    verifiedDate: '2026-09-23',
  },
  {
    id: 'KYC-503',
    applicantName: 'Sven Lindqvist (The Obsidian)',
    businessName: 'OBSIDIAN FINE ART STUDIOS',
    panNumber: 'BKIPL3391M',
    gstNumber: '08BKIPL3391M1ZP',
    aadhaarNumber: 'XXXX-XXXX-7729',
    docType: 'Aadhaar + Trade License',
    status: 'pending',
  },
  {
    id: 'KYC-504',
    applicantName: 'Devika Krishnan (Silk & Ivory)',
    businessName: 'SILK & IVORY NAIL LOUNGE',
    panNumber: 'CMPPK8821F',
    gstNumber: '29CMPPK8821F1ZX',
    aadhaarNumber: 'XXXX-XXXX-3341',
    docType: 'GSTIN + PAN',
    status: 'pending',
  },
];

export const initialQrTerminals: QrActivation[] = [
  {
    id: 'QR-001',
    terminalCode: 'NEX-TRM-MUM-01',
    salonId: 'SHOP-101',
    salonName: "L'Étoile Hair Lounge (Main Desk)",
    deskNumber: 'Desk A - Cashier & Concierge',
    upiVpa: 'letoile.salon@hdfcbank',
    status: 'active',
    hardwareModel: 'Nexora Gold Obsidian 10" OLED Stand',
    lastPing: '2 mins ago (Online)',
    activatedAt: '2026-09-21',
  },
  {
    id: 'QR-002',
    terminalCode: 'NEX-TRM-MUM-02',
    salonId: 'SHOP-101',
    salonName: "L'Étoile Hair Lounge (VIP Bay)",
    deskNumber: 'Desk B - Private Suite 01',
    upiVpa: 'letoile.vip@hdfcbank',
    status: 'active',
    hardwareModel: 'Nexora Gold Wireless NFC Pod',
    lastPing: '4 mins ago (Online)',
    activatedAt: '2026-09-22',
  },
  {
    id: 'QR-003',
    terminalCode: 'NEX-TRM-DEL-01',
    salonId: 'SHOP-102',
    salonName: 'AURA Luxury Spa (Reception)',
    deskNumber: 'Main Sanctuary Welcome Desk',
    upiVpa: 'auraspa.settle@icici',
    status: 'active',
    hardwareModel: 'Nexora Gold Obsidian 10" OLED Stand',
    lastPing: '1 min ago (Online)',
    activatedAt: '2026-09-24',
  },
  {
    id: 'QR-004',
    terminalCode: 'NEX-TRM-JAI-01',
    salonId: 'SHOP-103',
    salonName: 'The Obsidian Atelier',
    deskNumber: 'Counter 1 - Artist Station',
    upiVpa: 'obsidian.studio@axisbank',
    status: 'inactive',
    hardwareModel: 'Nexora Gold Obsidian Stand (V2)',
    lastPing: 'Never (Device in Transit)',
  },
];

export const initialDailyTransactions: DailyTransaction[] = [
  {
    id: 'TXN-9091',
    txnId: 'NEX-TXN-20260928-8812',
    date: '2026-09-28',
    time: '15:42:10',
    salonName: "L'Étoile Hair Lounge",
    clientName: 'Suhana Kapoor',
    serviceRendered: 'Signature French Gold Balayage',
    grossAmount: 18500,
    commission10: 1850,
    netPayoutToSalon: 16650,
    paymentMode: 'Gold QR UPI',
    status: 'settled',
  },
  {
    id: 'TXN-9092',
    txnId: 'NEX-TXN-20260928-8813',
    date: '2026-09-28',
    time: '15:20:04',
    salonName: 'AURA Luxury Spa',
    clientName: 'Vikram Oberoi',
    serviceRendered: 'Champagne & 24K Gold Body Healing',
    grossAmount: 22000,
    commission10: 2200,
    netPayoutToSalon: 19800,
    paymentMode: 'Escrow Vault',
    status: 'in_escrow',
  },
  {
    id: 'TXN-9093',
    txnId: 'NEX-TXN-20260928-8814',
    date: '2026-09-28',
    time: '14:55:30',
    salonName: "L'Étoile Hair Lounge",
    clientName: 'Pooja Hegde',
    serviceRendered: 'Royal Caviar Crown Therapy',
    grossAmount: 9500,
    commission10: 950,
    netPayoutToSalon: 8550,
    paymentMode: 'Gold QR UPI',
    status: 'settled',
  },
  {
    id: 'TXN-9094',
    txnId: 'NEX-TXN-20260928-8815',
    date: '2026-09-28',
    time: '14:10:19',
    salonName: 'The Obsidian Atelier',
    clientName: 'Aryaman Birla',
    serviceRendered: 'Bespoke Fine-Line Illustration',
    grossAmount: 25000,
    commission10: 2500,
    netPayoutToSalon: 22500,
    paymentMode: 'Concierge Card',
    status: 'settled',
  },
  {
    id: 'TXN-9095',
    txnId: 'NEX-TXN-20260928-8816',
    date: '2026-09-28',
    time: '13:40:02',
    salonName: 'AURA Luxury Spa',
    clientName: 'Tara Sutaria',
    serviceRendered: 'Elite Oxygen Facial Infusion',
    grossAmount: 14000,
    commission10: 1400,
    netPayoutToSalon: 12600,
    paymentMode: 'Gold QR UPI',
    status: 'settled',
  },
];

export const initialSettlements: SettlementRecord[] = [
  {
    id: 'SET-901',
    cycleCode: 'SET-CYC-2026-09-B',
    salonName: "L'Étoile Hair Lounge",
    grossVolume: 420000,
    commission10: 42000,
    tdsDeducted: 4200,
    netPayable: 373800,
    status: 'confirmed',
    utrNumber: 'HDFC99824108',
    dueDate: '2026-09-30',
    confirmedDate: '2026-09-28',
  },
  {
    id: 'SET-902',
    cycleCode: 'SET-CYC-2026-09-B',
    salonName: 'AURA Luxury Spa',
    grossVolume: 680000,
    commission10: 68000,
    tdsDeducted: 6800,
    netPayable: 605200,
    status: 'pending',
    dueDate: '2026-09-30',
  },
  {
    id: 'SET-903',
    cycleCode: 'SET-CYC-2026-09-B',
    salonName: 'The Obsidian Atelier',
    grossVolume: 290000,
    commission10: 29000,
    tdsDeducted: 2900,
    netPayable: 258100,
    status: 'pending',
    dueDate: '2026-09-30',
  },
];

export const initial15DayCounters: Automated15DayCounter[] = [
  {
    id: 'CTR-15-01',
    salonName: "L'Étoile Hair Lounge",
    cycleStart: '2026-09-15',
    cycleEnd: '2026-09-30',
    daysRemaining: 2,
    autoTriggerDate: '2026-09-30 23:59:59',
    accruedAmount: 512400,
    cycleNumber: 18,
    status: 'counting',
  },
  {
    id: 'CTR-15-02',
    salonName: 'AURA Luxury Spa',
    cycleStart: '2026-09-15',
    cycleEnd: '2026-09-30',
    daysRemaining: 2,
    autoTriggerDate: '2026-09-30 23:59:59',
    accruedAmount: 784000,
    cycleNumber: 14,
    status: 'counting',
  },
  {
    id: 'CTR-15-03',
    salonName: 'The Obsidian Atelier',
    cycleStart: '2026-09-15',
    cycleEnd: '2026-09-30',
    daysRemaining: 2,
    autoTriggerDate: '2026-09-30 23:59:59',
    accruedAmount: 345000,
    cycleNumber: 9,
    status: 'counting',
  },
  {
    id: 'CTR-15-04',
    salonName: 'Silk & Ivory Nail Lounge',
    cycleStart: '2026-09-20',
    cycleEnd: '2026-10-05',
    daysRemaining: 7,
    autoTriggerDate: '2026-10-05 23:59:59',
    accruedAmount: 148000,
    cycleNumber: 3,
    status: 'counting',
  },
];

export const initialMilestonePlusOnes: MilestonePlusOne[] = [
  {
    id: 'MLS-101',
    partnerOrSalon: 'Kunal Singhania (Growth Partner)',
    role: 'Growth Partner',
    currentCount: 14,
    targetCount: 15,
    plusOneMilestoneName: '15th Tier-1 Salon Acquisition (+1 Milestone)',
    bonusReward: '₹1,50,000 Cash Grant + Rolex Submariner Voucher',
    plusOneStatus: 'pending_validation',
    validationDoc: 'MOU_Silk_Ivory_Signed.pdf',
  },
  {
    id: 'MLS-102',
    partnerOrSalon: "L'Étoile Hair Lounge",
    role: 'Luxury Salon',
    currentCount: 999,
    targetCount: 1000,
    plusOneMilestoneName: '1,000th Verified VIP Booking (+1 Century Milestone)',
    bonusReward: 'Zero Commission for 30 Days + Gold Plaque',
    plusOneStatus: 'pending_validation',
    validationDoc: 'Audit_Booking_1000th.pdf',
  },
  {
    id: 'MLS-103',
    partnerOrSalon: 'Meera Rajput (Growth Partner)',
    role: 'Growth Partner',
    currentCount: 10,
    targetCount: 10,
    plusOneMilestoneName: '10 Salons Onboarded (+1 Milestone Unlocked)',
    bonusReward: 'Paris Haute Couture Trip for 2',
    plusOneStatus: 'bonus_unlocked',
    validationDoc: 'Onboarding_Audit_10_Salons.pdf',
  },
];

export const initialDuplicateShops: DuplicateShop[] = [
  {
    id: 'DUP-001',
    candidateName: "L'Etoile Hair Studio Bandra East",
    existingMatchName: "L'Étoile Hair Lounge (Bandra West)",
    matchScore: 94,
    phone: '+91 98200 99124 (Exact match with Owner mobile)',
    geoDistance: '1.2 km away',
    reason: 'Identical GSTIN and owner contact detected; possible duplicate branch onboarding attempt.',
    status: 'flagged',
  },
  {
    id: 'DUP-002',
    candidateName: 'Aura Wellness Studio GK2',
    existingMatchName: 'AURA Luxury Thermal Spa (Vasant Vihar)',
    matchScore: 78,
    phone: '+91 98111 88392 (Linked corporate group)',
    geoDistance: '8.4 km away',
    reason: 'Trademark similarity & common director detected; verify if legitimate franchise or clone.',
    status: 'flagged',
  },
];

export const initialFraudAlerts: FraudAlert[] = [
  {
    id: 'FRD-401',
    severity: 'critical',
    type: 'Velocity Spike Anomaly',
    entityName: 'Glamour Vault (Unverified Mumbai Outlet)',
    flaggedAmount: 185000,
    description: '14 consecutive transactions of ₹13,200 within 6 minutes on single QR code with generic UPI handles.',
    timestamp: '2026-09-28 14:02:18',
    status: 'frozen',
  },
  {
    id: 'FRD-402',
    severity: 'high',
    type: 'Chargeback & Geo Mismatch',
    entityName: 'Radiance Spa & Salon',
    flaggedAmount: 48000,
    description: 'UPI client device IP located in Kyiv, Ukraine while QR scan registered at Pune physical counter.',
    timestamp: '2026-09-28 12:44:09',
    status: 'investigating',
  },
  {
    id: 'FRD-403',
    severity: 'moderate',
    type: 'Repeated Cancel After Escrow Lock',
    entityName: 'Obsidian Guest User #8821',
    flaggedAmount: 25000,
    description: '3 cancellations triggered within 2 minutes of stylist appointment locking.',
    timestamp: '2026-09-28 10:18:33',
    status: 'cleared',
  },
];

export const initialRewardClaims: RewardClaim[] = [
  {
    id: 'RWD-301',
    claimantName: 'Kunal Singhania',
    role: 'Growth Partner',
    tierLevel: 'Diamond Tier (14 Salons)',
    rewardTitle: 'Nexora 24K Pure Gold Executive Desk Emblem (100g)',
    claimDate: '2026-09-25',
    status: 'approved',
    dispatchTracking: 'BLUEDART-LUX-882910',
  },
  {
    id: 'RWD-302',
    claimantName: "Master Jean-Jacques (L'Étoile)",
    role: 'Salon Master',
    tierLevel: 'Couture House of the Quarter',
    rewardTitle: 'Dyson Supersonic Gold Professional Kit + Champagne Cask',
    claimDate: '2026-09-27',
    status: 'submitted',
  },
  {
    id: 'RWD-303',
    claimantName: 'Meera Rajput',
    role: 'Growth Partner',
    tierLevel: 'Platinum Tier (9 Salons)',
    rewardTitle: 'Montblanc Meisterstück Gold-Coated Fountain Pen',
    claimDate: '2026-09-28',
    status: 'submitted',
  },
];

export const initialProducts: ProductItem[] = [
  {
    id: 'PRD-01',
    sku: 'NX-CAV-250',
    name: 'French White Caviar Scalp Serum (250ml)',
    brand: "L'Étoile Atelier Paris",
    category: 'Hair Artistry & Care',
    price: 8500,
    stockUnits: 42,
    status: 'in_stock',
    luxuryGrade: 'Grade AAA Marine Extract',
  },
  {
    id: 'PRD-02',
    sku: 'NX-GLD-100',
    name: '24K Liquid Gold Rejuvenation Elixir (100ml)',
    brand: 'AURA Thermal Alchemy',
    category: 'Spa & Body Rituals',
    price: 14000,
    stockUnits: 18,
    status: 'in_stock',
    luxuryGrade: 'Cert 999.9 Fine Gold Flakes',
  },
  {
    id: 'PRD-03',
    sku: 'NX-OBS-PIG',
    name: 'Obsidian Hypoallergenic Carbon Pigment (50ml)',
    brand: 'The Obsidian Ink House',
    category: 'Ink Artistry Supplies',
    price: 6200,
    stockUnits: 8,
    status: 'low_stock',
    luxuryGrade: 'Surgical Grade Pigment',
  },
  {
    id: 'PRD-04',
    sku: 'NX-KER-500',
    name: 'Micro-Keratin Thermal Bond Infusion (500ml)',
    brand: "L'Étoile Atelier Paris",
    category: 'Hair Artistry & Care',
    price: 11500,
    stockUnits: 34,
    status: 'in_stock',
    luxuryGrade: 'Hydrolyzed Silk Protein',
  },
];

export const initialVendors: VendorDealer[] = [
  {
    id: 'VND-201',
    vendorName: 'Maison de Beaute Paris Imports',
    contactPerson: 'Alexandre Laurent',
    contactPhone: '+33 1 42 68 55 00',
    category: 'Hair Pigments & Caviar Extracts',
    rating: 4.96,
    slaTerms: '48h White-Glove Air Dispatch to Mumbai / Delhi Hubs',
    contractExpiry: '2027-12-31',
    status: 'active',
  },
  {
    id: 'VND-202',
    vendorName: 'Swiss Alpine Thermal Tech AG',
    contactPerson: 'Greta Meyer',
    contactPhone: '+41 22 819 90 20',
    category: 'Thermal Spa Equipment & Hydrotherapy Pods',
    rating: 4.98,
    slaTerms: 'Annual On-Site Calibration & 24/7 Remote Telemetry',
    contractExpiry: '2028-06-30',
    status: 'active',
  },
  {
    id: 'VND-203',
    vendorName: 'Titanium & Gold Craft Piercing Japan',
    contactPerson: 'Kenji Takahashi',
    contactPhone: '+81 3 5555 0192',
    category: 'Surgical Titanium & 18K Solid Gold Body Adornments',
    rating: 4.92,
    slaTerms: 'Batch Autoclave Certificate with every shipping box',
    contractExpiry: '2026-11-30',
    status: 'active',
  },
];

export const initialInvoices: InvoiceRecord[] = [
  {
    id: 'INV-1091',
    invoiceNumber: 'NX-INV-2026-09-082',
    salonOrVendor: "L'Étoile Hair Lounge",
    invoiceDate: '2026-09-25',
    grossAmount: 42000,
    gstAmount: 7560,
    type: 'Platform 10% Fee',
    fileAttachment: 'INV_Letoile_Sep25.pdf',
    status: 'verified',
  },
  {
    id: 'INV-1092',
    invoiceNumber: 'NX-INV-2026-09-083',
    salonOrVendor: 'AURA Luxury Spa',
    invoiceDate: '2026-09-26',
    grossAmount: 68000,
    gstAmount: 12240,
    type: 'Platform 10% Fee',
    fileAttachment: 'INV_Aura_Sep26.pdf',
    status: 'verified',
  },
  {
    id: 'INV-1093',
    invoiceNumber: 'NX-INV-2026-09-084',
    salonOrVendor: 'Silk & Ivory Nail Lounge',
    invoiceDate: '2026-09-28',
    grossAmount: 35000,
    gstAmount: 6300,
    type: 'Hardware Terminal',
    fileAttachment: 'INV_SilkIvory_Terminal.pdf',
    status: 'pending_review',
  },
];

export const initialTaxTds: TaxTdsStatus[] = [
  {
    id: 'TDS-701',
    entityName: "LETOILE LUXURY SALONS LLP",
    pan: 'AAFFL8891K',
    grossTurnover: 4200000,
    tdsSection: '194O (1% E-comm)',
    tdsAmount: 42000,
    challanNumber: 'CIN-0029817290182',
    quarter: 'Q2 (Jul - Sep 2026)',
    status: 'deposited',
  },
  {
    id: 'TDS-702',
    entityName: 'AURA THERAPEUTICS INDIA PVT LTD',
    pan: 'AACCA4491J',
    grossTurnover: 6800000,
    tdsSection: '194O (1% E-comm)',
    tdsAmount: 68000,
    challanNumber: 'CIN-0029817290183',
    quarter: 'Q2 (Jul - Sep 2026)',
    status: 'deposited',
  },
  {
    id: 'TDS-703',
    entityName: 'Kunal Singhania (Growth Partner)',
    pan: 'BHPPS9912A',
    grossTurnover: 385000,
    tdsSection: '194C (2% Contractor)',
    tdsAmount: 7700,
    challanNumber: 'PENDING-CHALLAN-GEN',
    quarter: 'Q2 (Jul - Sep 2026)',
    status: 'pending_challan',
  },
];

export const initialDispatches: DispatchRecord[] = [
  {
    id: 'DSP-801',
    awbNumber: 'BD-LUX-99812401',
    recipientName: "Master Jean-Jacques",
    salonName: "L'Étoile Hair Lounge",
    destinationCity: 'Mumbai (Bandra West)',
    packageType: 'Gold QR Terminal Kit + Obsidian Desk Stand',
    courierPartner: 'Blue Dart Luxury Secured Express',
    dispatchDate: '2026-09-20',
    status: 'delivered',
  },
  {
    id: 'DSP-802',
    awbNumber: 'BD-LUX-99812402',
    recipientName: 'Dr. Kabir Sethi',
    salonName: 'AURA Luxury Spa',
    destinationCity: 'New Delhi (Vasant Vihar)',
    packageType: '2x Gold NFC Desk Pods + VIP Client Welcome Envelopes',
    courierPartner: 'Nexora White-Glove Courier',
    dispatchDate: '2026-09-22',
    status: 'delivered',
  },
  {
    id: 'DSP-803',
    awbNumber: 'BD-LUX-99812403',
    recipientName: 'Sven Lindqvist',
    salonName: 'The Obsidian Atelier',
    destinationCity: 'Jaipur (C-Scheme)',
    packageType: 'Gold Terminal Stand + 10x NFC Concierge Cards',
    courierPartner: 'Blue Dart Luxury Secured Express',
    dispatchDate: '2026-09-27',
    status: 'in_transit',
  },
];

export const initialVehicles: VehicleRecord[] = [
  {
    id: 'VEH-01',
    vehicleNumber: 'MH 02 EQ 0007',
    model: 'Mercedes-Benz S-Class Maybach (Black Obsidian)',
    driverName: 'Ramprasad Sharma',
    driverPhone: '+91 98201 11223',
    assignedRole: 'VIP Guest Pick-Up Chauffeur',
    inspectionStatus: 'certified',
    permitExpiry: '2027-08-15',
  },
  {
    id: 'VEH-02',
    vehicleNumber: 'DL 01 CAB 8888',
    model: 'BMW 7 Series Protection Spec (Metallic Gold/Black)',
    driverName: 'Harvinder Singh',
    driverPhone: '+91 98110 33445',
    assignedRole: 'VIP Guest Pick-Up Chauffeur',
    inspectionStatus: 'certified',
    permitExpiry: '2027-06-20',
  },
  {
    id: 'VEH-03',
    vehicleNumber: 'MH 04 DZ 9901',
    model: 'Toyota Vellfire Luxury Executive Lounge',
    driverName: 'Sanjay Jadhav',
    driverPhone: '+91 98209 55667',
    assignedRole: 'Express Supply Courier',
    inspectionStatus: 'pending_audit',
    permitExpiry: '2026-10-30',
  },
];

export const initialComplaints: ComplaintAppeal[] = [
  {
    id: 'CMP-601',
    ticketId: 'TCK-2026-0812',
    filedBy: 'Ananya Singhania (VIP Client)',
    role: 'Guest VIP',
    priority: 'high',
    subject: 'Escrow payment debited twice during server peak',
    details: '₹18,500 authorization hold held on primary card, but secondary UPI also cleared at desk.',
    status: 'resolved',
    resolutionNotes: 'Instant reverse credit initiated via Razorpay UTR #991823. Duplicate hold lifted within 15 minutes.',
    filedDate: '2026-09-27',
  },
  {
    id: 'CMP-602',
    ticketId: 'TCK-2026-0813',
    filedBy: "Master Jean-Jacques (L'Étoile)",
    role: 'Salon Owner',
    priority: 'normal',
    subject: 'TDS certificate Form 16A download query for Q1',
    details: 'Accountant requested digitally signed Form 16A PDF for IT return filing.',
    status: 'in_arbitration',
    resolutionNotes: 'Compliance team preparing TRACES consolidated certificate by Sep 30.',
    filedDate: '2026-09-28',
  },
];
