// Edge Function: generate-bio
// POST { businessName, businessType, ownerName, vibe, specialties }
// Returns { tagline, bio } generated by Gemini (with graceful fallback).
import { GoogleGenAI } from "https://esm.sh/@google/genai@2.4.0";
import { handleOptions, ok, fail } from "../_shared/cors.ts";

const MODEL = "gemini-1.5-flash";

function fallback(body: any): { tagline: string; bio: string } {
  const type = (body.businessType || "beauty").replace(/_/g, " ");
  return {
    tagline: `Elevating ${type} with bespoke luxury & precision care.`,
    bio: `Welcome to ${body.businessName || "our studio"}, founded by ${
      body.ownerName || "our team"
    }. We are a modern sanctuary dedicated to ${
      body.specialties || "exceptional salon services"
    }. Blending a ${
      body.vibe || "luxury"
    } aesthetic with high-performance organic products, our mission is to make every client feel renewed and confident.`,
  };
}

async function handler(req: Request): Promise<Response> {
  if (req.method === "OPTIONS") return handleOptions(req);
  if (req.method !== "POST") return fail("Method not allowed", 405);

  let body: any = {};
  try {
    body = await req.json();
  } catch {
    /* no body */
  }

  const apiKey = Deno.env.get("GEMINI_API_KEY");
  if (!apiKey) return ok(fallback(body));

  try {
    const ai = new GoogleGenAI({ apiKey });
    const prompt = `Write a high-converting tagline (max 10 words) and a compelling salon story/about bio (2-3 sentences) for a beauty business with the following details:
Salon Name: ${body.businessName}
Category: ${body.businessType}
Founder: ${body.ownerName}
Atmosphere/Vibe: ${body.vibe}
Specialties: ${body.specialties}

Return strictly valid JSON in this format:
{"tagline": "...", "bio": "..."}`;

    const response = await ai.models.generateContent({
      model: MODEL,
      contents: prompt,
      config: { responseMimeType: "application/json" },
    });
    const text = response.text;
    if (text) return ok(JSON.parse(text));
    return ok(fallback(body));
  } catch (err: any) {
    console.warn("generate-bio error:", err?.message || err);
    return ok(fallback(body));
  }
}

Deno.serve(handler);
