import React, { useCallback, useEffect, useState } from 'react';
import { Bell, Check, ChevronDown, Download, FileText, HelpCircle, IndianRupee, Medal, MessageCircle, Send, Trophy, Wallet } from 'lucide-react';
import { PartnerToast } from './PartnerToast';
import { getPartnerEarnings, getPartnerLeaderboard, getPartnerLevels, getPartnerMarketingAssets, getPartnerNotifications, markPartnerNotificationsRead, requestPartnerPayout, submitPartnerSupportTicket, type PartnerEarningsPayload, type PartnerLeaderboardPayload, type PartnerLevelsPayload, type PartnerMarketingAsset, type PartnerNotificationsPayload } from '../lib/partnerPortalOperations';

const money = (paise: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format((Number(paise) || 0) / 100);
const Button = ({ children, onClick, secondary = false, type = 'button' }: { children: React.ReactNode; onClick?: () => void; secondary?: boolean; type?: 'button' | 'submit' }) => <button type={type} onClick={onClick} className={`inline-flex min-h-11 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${secondary ? 'bg-slate-100 text-slate-800' : 'bg-slate-900 text-white'}`}>{children}</button>;
const Card = ({ label, value, hint }: { label: string; value: string; hint?: string }) => <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-2xl font-black">{value}</p><p className="mt-1 text-sm font-bold text-slate-600">{label}</p>{hint ? <p className="mt-1 text-xs text-slate-500">{hint}</p> : null}</div>;
const Loading = () => <p className="rounded-2xl bg-slate-100 p-4 text-sm font-semibold text-slate-500">Loading live partner data…</p>;

export function PartnerEarningsModule() {
  const [data, setData] = useState<PartnerEarningsPayload | null>(null), [error, setError] = useState('');
  useEffect(() => { void getPartnerEarnings().then(setData).catch(e => setError(e.message)); }, []);
  if (!data && !error) return <Loading />;
  return <div className="space-y-5"><section className="rounded-3xl bg-gradient-to-br from-slate-950 to-[#8b0a46] p-6 text-white"><Wallet className="h-8 w-8 text-pink-200" /><h2 className="mt-4 text-2xl font-black">Your earnings</h2><p className="text-sm text-slate-200">Live recurring subscription commissions.</p></section>{error ? <p className="text-rose-700">{error}</p> : null}<section className="grid gap-4 sm:grid-cols-3"><Card label="Lifetime earnings" value={money(data?.totals.lifetime_paise ?? 0)} /><Card label="Pending" value={money(data?.totals.pending_paise ?? 0)} hint="Available seven days after clearance" /><Card label="Available to withdraw" value={money(data?.totals.available_paise ?? 0)} /></section><section className="overflow-hidden rounded-3xl border bg-white"><div className="flex justify-between border-b p-5"><h2 className="font-black">Transaction history</h2><Button secondary onClick={() => window.print()}><FileText className="h-4" />PDF</Button></div>{(data?.transactions ?? []).map(x => <div key={x.id} className="flex justify-between border-b p-4 text-sm"><span className="capitalize">{x.earning_type.replaceAll('_',' ')}</span><span>{x.status.replaceAll('_',' ')}</span><strong>{money(x.amount_paise)}</strong></div>)}</section></div>;
}

export function PartnerWithdrawalsModule() {
  const [earnings, setEarnings] = useState<PartnerEarningsPayload | null>(null), [open, setOpen] = useState(false), [amount, setAmount] = useState(''), [method, setMethod] = useState('upi'), [notice, setNotice] = useState('');
  const load = useCallback(() => void getPartnerEarnings().then(setEarnings).catch(e => setNotice(e.message)), []); useEffect(load, [load]);
  const submit = () => { const paise = Math.round(Number(amount) * 100); void requestPartnerPayout(paise, method, `${method} destination`).then(x => { setNotice(`Withdrawal request is ${x.status}.`); setOpen(false); setAmount(''); load(); }).catch(e => setNotice(e.message)); };
  return <div className="space-y-5"><PartnerToast message={notice} noticeId={notice.length} /><section className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-sm font-bold text-pink-200">Available to withdraw</p><p className="mt-2 text-4xl font-black">{money(earnings?.totals.available_paise ?? 0)}</p><Button onClick={() => setOpen(true)}><IndianRupee className="h-4" />Request withdrawal</Button></section>{open ? <section className="rounded-3xl border bg-white p-6"><h2 className="font-black">Request withdrawal</h2><input value={amount} onChange={e => setAmount(e.target.value)} placeholder="Amount in ₹" className="mt-3 w-full rounded-xl border p-3" /><select value={method} onChange={e => setMethod(e.target.value)} className="mt-3 w-full rounded-xl border p-3"><option value="upi">UPI</option><option value="bank_transfer">Bank transfer</option><option value="paypal">PayPal</option></select><div className="mt-3 flex gap-2"><Button onClick={submit}>Submit</Button><Button secondary onClick={() => setOpen(false)}>Cancel</Button></div></section> : null}</div>;
}

export function PartnerMarketingMaterialsModule() { const [assets, setAssets] = useState<PartnerMarketingAsset[]>([]), [error, setError] = useState(''); useEffect(() => { void getPartnerMarketingAssets().then(setAssets).catch(e => setError(e.message)); }, []); return <div className="space-y-5"><section className="rounded-3xl bg-gradient-to-br from-[#8b0a46] to-[#ed176f] p-6 text-white"><h2 className="text-2xl font-black">Marketing materials</h2><p className="text-sm text-pink-100">Published assets from the partner library.</p></section>{error ? <p className="text-rose-700">{error}</p> : null}<section className="grid gap-4 md:grid-cols-2">{assets.map(a => <article key={a.id} className="rounded-3xl border bg-white p-5"><FileText className="h-8 text-[#c20e5a]" /><p className="mt-3 text-xs uppercase text-slate-500">{a.category}</p><h3 className="font-black">{a.title}</h3><p className="mt-1 text-sm text-slate-600">{a.description}</p><Button secondary onClick={() => setError('Downloads will use signed Storage URLs when assets are uploaded.')}><Download className="h-4" />Download</Button></article>)}{!assets.length ? <p className="text-slate-500">No published assets yet.</p> : null}</section></div>; }

export function PartnerLevelsModule() { const [data, setData] = useState<PartnerLevelsPayload | null>(null); useEffect(() => { void getPartnerLevels().then(setData); }, []); if (!data) return <Loading />; return <div className="space-y-5"><section className="rounded-3xl bg-slate-950 p-6 text-white"><Medal className="h-8 text-amber-300" /><h2 className="mt-3 text-2xl font-black">Partner levels</h2><p>{data.active_referrals} active referrals</p></section><section className="grid gap-4 lg:grid-cols-4">{data.levels.map(x => <article key={x.code} className={`rounded-3xl border bg-white p-5 ${x.unlocked ? 'border-[#c20e5a]' : ''}`}><p className="font-black capitalize">{x.code}</p><p className="mt-2 text-2xl font-black text-[#c20e5a]">{x.commission_bps / 100}%</p><p className="text-xs text-slate-500">From {x.minimum_paid_referrals} active referrals</p></article>)}</section></div>; }

export function PartnerLeaderboardsModule() { const [data, setData] = useState<PartnerLeaderboardPayload | null>(null); useEffect(() => { void getPartnerLeaderboard().then(setData); }, []); if (!data) return <Loading />; return <div className="space-y-5"><section className="rounded-3xl bg-slate-950 p-6 text-white"><Trophy className="h-8 text-amber-300" /><h2 className="mt-3 text-2xl font-black">Partner leaderboard</h2><p>Your rank: {data.my_rank ? `#${data.my_rank}` : 'Unranked'}</p></section><section className="overflow-hidden rounded-3xl border bg-white">{data.items.map(x => <div key={x.partner_id} className="flex justify-between border-b p-4"><span className="font-bold">#{x.rank}</span><span>{money(x.earnings_paise)}</span></div>)}</section></div>; }

export function PartnerNotificationsModule() { const [data, setData] = useState<PartnerNotificationsPayload | null>(null); const load = useCallback(() => void getPartnerNotifications().then(setData), []); useEffect(load, [load]); if (!data) return <Loading />; return <div className="space-y-4"><div className="flex justify-between"><div><h2 className="text-2xl font-black">Notifications</h2><p>{data.unread_count} unread</p></div><Button secondary onClick={() => void markPartnerNotificationsRead().then(load)}><Check className="h-4" />Mark all read</Button></div><section className="overflow-hidden rounded-3xl border bg-white">{data.items.map(x => <div key={x.id} className="border-b p-5"><p className="font-bold"><Bell className="mr-2 inline h-4" />{x.title}</p><p className="mt-1 text-sm text-slate-600">{x.body}</p></div>)}</section></div>; }

export function PartnerSupportModule() { const [query,setQuery]=useState(''), [open,setOpen]=useState<number|null>(null), [notice,setNotice]=useState(''); const faq=[['When are earnings available?','Seven days after subscription payment clearance.'],['How do I request a payout?','Submit at least ₹500 from Withdrawals.']].filter(x=>x.join(' ').toLowerCase().includes(query.toLowerCase())); return <div className="space-y-5"><PartnerToast message={notice} noticeId={notice.length} /><section className="rounded-3xl bg-slate-950 p-6 text-white"><HelpCircle className="h-8" /><h2 className="mt-3 text-2xl font-black">Support</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search FAQs" className="mt-3 w-full rounded-xl p-3 text-slate-900" /></section><section className="rounded-3xl border bg-white">{faq.map(([q,a],i)=><div key={q} className="border-b"><button onClick={()=>setOpen(open===i?null:i)} className="flex w-full justify-between p-4 text-left font-bold">{q}<ChevronDown className="h-4" /></button>{open===i?<p className="px-4 pb-4 text-sm">{a}</p>:null}</div>)}</section><form onSubmit={e=>{e.preventDefault(); const f=new FormData(e.currentTarget); void submitPartnerSupportTicket(String(f.get('subject')),String(f.get('message'))).then(x=>{setNotice(`Ticket #${x.ticket_number} submitted.`);e.currentTarget.reset()}).catch(x=>setNotice(x.message));}} className="rounded-3xl border bg-white p-6"><h2 className="font-black">Submit a ticket</h2><input required name="subject" placeholder="Subject" className="mt-3 w-full rounded-xl border p-3"/><textarea required name="message" placeholder="Describe the issue" className="mt-3 min-h-28 w-full rounded-xl border p-3"/><Button type="submit"><Send className="h-4"/>Submit ticket</Button></form><a href="https://wa.me/" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700"><MessageCircle className="h-4"/>WhatsApp support</a></div>; }
