import { BusinessTypeOption, SalonProfile, SalonService, Stylist, Appointment, ClientRecord } from './types';
import { CATEGORY_TEMPLATES, ALL_CATEGORY_OPTIONS } from './categoryTemplates';

export const BUSINESS_TYPES: BusinessTypeOption[] = ALL_CATEGORY_OPTIONS;

// Default to Arts By Uma
const defaultTemplate = CATEGORY_TEMPLATES.hair_salon;

export const INITIAL_SALON_PROFILE: SalonProfile = {
  businessType: 'hair_salon',
  businessName: 'Arts By Uma',
  ownerName: 'Uma',
  ownerRole: 'Founder & Master Stylist',
  phone: '+91 98450 77654',
  whatsapp: '+91 98450 77654',
  email: 'hello@artsbyuma.com',
  tagline: 'Precision Cuts, Creative Hair Artistry & Luxury Nail Lounge',
  about: 'Welcome to Arts By Uma. Founded by Uma, our boutique studio brings together master precision haircuts, bespoke balayage, sculpted gel nail art, and restorative hair spa therapies in a luxury sanctuary. We craft personalized looks that elevate your confidence and natural beauty.',
  ownerPhotoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=500&q=80',
  coverImageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=80',
  themePreset: 'slate_silver',
  themeAccentKey: 'slate',
  currency: '₹',
  subdomain: 'arts-by-uma',
  address: '100 Feet Road, 12th Main, Indiranagar',
  city: 'Bengaluru, Karnataka',
  postalCode: '560038',
  instagramHandle: '@arts_by_uma',
  facebookPage: 'https://facebook.com/artsbyuma',
  tiktokHandle: '@artsbyuma',
  tiktokProfile: 'https://tiktok.com/@artsbyuma',
  requireDeposit: true,
  depositPercentage: 20,
  whiteLabelEnabled: true,
  promotionalBanner: {
    enabled: true,
    text: '✨ Festive Season Special: Get Flat 20% OFF on all Precision Styling & Balayage packages!',
    discountCode: 'FESTIVE20',
    badgeText: 'LIMITED OFFER',
    buttonText: 'Claim 20% OFF',
    buttonAction: 'book',
    themePreset: 'royal_gold',
  },
};

export const INITIAL_SERVICES: SalonService[] = [
  {
    id: 'hs-1',
    name: 'Master Stylist Precision Cut & Blowdry',
    category: 'Hair Artistry',
    durationMinutes: 45,
    price: 750,
    description: 'Sculpted haircut tailored to face geometry, invigorating scalp wash, and professional salon blowout.',
    icon: 'content_cut',
    popular: true,
    showDuration: true,
  },
  {
    id: 'hs-2',
    name: 'Classic Layered Cut & Argan Wash',
    category: 'Hair Artistry',
    durationMinutes: 35,
    price: 450,
    description: 'Texturizing layers, split-end removal, and deep cleanse with organic Moroccan argan oil shampoo.',
    icon: 'styler',
    popular: false,
    showDuration: true,
  },
  {
    id: 'hs-3',
    name: 'Signature Caramel Balayage & Olaplex Glaze',
    category: 'Color Alchemy',
    durationMinutes: 150,
    price: 5200,
    description: 'Custom hand-painted multidimensional caramel, copper, or hazelnut highlights with bonded Olaplex protection.',
    icon: 'palette',
    popular: true,
    showDuration: true,
  },
  {
    id: 'hs-4',
    name: 'Full Set Gel-X Sculpted Extensions & Nail Art',
    category: 'Nail Couture',
    durationMinutes: 90,
    price: 2400,
    description: 'Damage-free soft gel tips custom fitted to your natural nail bed with custom handpainted art and glossy UV seal.',
    icon: 'pan_tool_alt',
    popular: true,
    showDuration: true,
  },
  {
    id: 'hs-5',
    name: 'Formaldehyde-Free Keratin Smoothing',
    category: 'Treatments',
    durationMinutes: 120,
    price: 4200,
    description: 'Infuses active keratin proteins, eliminating 95% frizz with mirror-like shine for up to 14 weeks.',
    icon: 'auto_fix_high',
    popular: true,
    showDuration: true,
  },
  {
    id: 'hs-6',
    name: 'Hair Botox Deep Fiber Reconstruction',
    category: 'Treatments',
    durationMinutes: 90,
    price: 3600,
    description: 'Intense peptide filler mask for chemically damaged or heat-stressed hair fibers.',
    icon: 'healing',
    popular: false,
    showDuration: true,
  },
  {
    id: 'hs-7',
    name: 'Red Carpet HD Glass Skin & Party Makeover',
    category: 'Editorial Glam',
    durationMinutes: 75,
    price: 4500,
    description: 'Flawless camera-ready HD base, soft contour, winged eyeliner, and magnetic flutter lashes.',
    icon: 'face_retouching_natural',
    popular: true,
    showDuration: true,
  },
  {
    id: 'hs-8',
    name: 'Russian Dry Cuticle Precision Manicure',
    category: 'Nail Couture',
    durationMinutes: 60,
    price: 1100,
    description: 'E-file precision diamond bit cuticle cleanup, keratin basecoat, and high-shine gel polish.',
    icon: 'auto_awesome',
    popular: false,
    showDuration: true,
  },
  {
    id: 'hs-9',
    name: 'Express Glow Organic Cleanup & De-Tan',
    category: 'Skin & Spa',
    durationMinutes: 40,
    price: 850,
    description: 'Gentle fruit peel scrub, pore steam, blackhead removal, and saffron brightening mask.',
    icon: 'spa',
    popular: false,
    showDuration: true,
  },
];

export const INITIAL_STYLISTS: Stylist[] = [
  {
    id: 'hs-st-uma',
    name: 'Uma',
    role: 'Founder & Master Stylist',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    bio: 'Founder with 12+ years of experience across London and Bengaluru salons. Specializes in precision structural cuts, dimensional color, and bespoke nail couture.',
    phone: '+91 98450 77654',
    specialties: ['Structural Cuts', 'Balayage Color', 'Keratin Smoothing', 'Gel-X Extensions'],
    assignedServices: ['hs-1', 'hs-3', 'hs-4', 'hs-5', 'hs-7'],
    rating: 4.98,
    commissionRate: 35,
    status: 'Available',
    accessRole: 'Manager (Full Access)',
    hidePhone: false,
    schedule: [],
  },
  {
    id: 'hs-st-1',
    name: 'Ananya Sharma',
    role: 'Senior Precision Stylist',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    bio: 'Senior colorist and stylist with extensive background in balayage, ombre, and volume blowouts.',
    phone: '+91 98450 12890',
    specialties: ['Precision Fringes', 'Balayage & Color', 'Volume Blowouts'],
    assignedServices: ['hs-1', 'hs-2', 'hs-3', 'hs-5'],
    rating: 4.95,
    commissionRate: 30,
    status: 'Available',
    accessRole: 'Service Provider (Assigned)',
    hidePhone: false,
    schedule: [],
  },
  {
    id: 'hs-st-2',
    name: 'Rohan Kapoor',
    role: 'Stylist & Hair Craftsman',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    bio: 'Men and women haircut specialist with expertise in dry cutting, skin fades, and textured styling.',
    phone: '+91 98450 33412',
    specialties: ['Dry Cutting', 'Men & Women Styling', 'Fade Geometry'],
    assignedServices: ['hs-1', 'hs-2', 'hs-6'],
    rating: 4.92,
    commissionRate: 25,
    status: 'Available',
    accessRole: 'Service Provider (Assigned)',
    hidePhone: false,
    schedule: [],
  },
  {
    id: 'hs-st-3',
    name: 'Kavita Deshmukh',
    role: 'Hair Texture & Scalp Specialist',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    bio: 'Trichology-trained scalp and hair botox specialist focusing on restorative therapies.',
    phone: '+91 98450 99881',
    specialties: ['Hair Botox', 'Scalp Analysis', 'Thermal Tongs'],
    assignedServices: ['hs-5', 'hs-6', 'hs-9'],
    rating: 4.89,
    commissionRate: 25,
    status: 'Available',
    accessRole: 'Service Provider (Assigned)',
    hidePhone: false,
    schedule: [],
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-ind-101',
    clientName: 'Pooja Mehra',
    clientPhone: '+91 98451 22910',
    clientEmail: 'pooja.mehra@gmail.com',
    serviceId: 'hs-3',
    serviceName: 'Signature Caramel Balayage & Olaplex Glaze',
    servicePrice: 5200,
    stylistId: 'hs-st-uma',
    stylistName: 'Uma',
    date: '2026-09-06',
    time: '11:00',
    status: 'confirmed',
    paymentStatus: 'paid_deposit',
    amountPaid: 1040,
    createdAt: '2026-09-04T10:15:00Z',
  },
  {
    id: 'apt-ind-102',
    clientName: 'Siddharth Verma',
    clientPhone: '+91 98201 44589',
    clientEmail: 'siddharth.verma@techcorp.in',
    serviceId: 'hs-1',
    serviceName: 'Master Stylist Precision Cut & Blowdry',
    servicePrice: 750,
    stylistId: 'hs-st-2',
    stylistName: 'Rohan Kapoor',
    date: '2026-09-06',
    time: '14:30',
    status: 'confirmed',
    paymentStatus: 'paid_full',
    amountPaid: 750,
    createdAt: '2026-09-04T14:45:00Z',
  },
  {
    id: 'apt-ind-103',
    clientName: 'Radhika Singhania',
    clientPhone: '+91 98110 55762',
    clientEmail: 'radhika.singh@outlook.com',
    serviceId: 'hs-4',
    serviceName: 'Full Set Gel-X Sculpted Extensions & Nail Art',
    servicePrice: 2400,
    stylistId: 'hs-st-uma',
    stylistName: 'Uma',
    date: '2026-09-07',
    time: '10:00',
    status: 'confirmed',
    paymentStatus: 'paid_deposit',
    amountPaid: 480,
    createdAt: '2026-09-05T09:20:00Z',
  },
  {
    id: 'apt-ind-104',
    clientName: 'Aditya Sen',
    clientPhone: '+91 98450 78129',
    clientEmail: 'aditya.sen@gmail.com',
    serviceId: 'hs-2',
    serviceName: 'Classic Layered Cut & Argan Wash',
    servicePrice: 450,
    stylistId: 'hs-st-1',
    stylistName: 'Ananya Sharma',
    date: '2026-09-07',
    time: '16:00',
    status: 'confirmed',
    paymentStatus: 'pay_at_salon',
    amountPaid: 0,
    createdAt: '2026-09-05T11:00:00Z',
  },
  {
    id: 'apt-ind-105',
    clientName: 'Kavya Nambiar',
    clientPhone: '+91 97412 88301',
    clientEmail: 'kavya.nambiar@gmail.com',
    serviceId: 'hs-5',
    serviceName: 'Formaldehyde-Free Keratin Smoothing',
    servicePrice: 4200,
    stylistId: 'hs-st-uma',
    stylistName: 'Uma',
    date: '2026-07-15',
    time: '12:30',
    status: 'completed',
    paymentStatus: 'paid_full',
    amountPaid: 4200,
    createdAt: '2026-07-12T10:00:00Z',
  },
  {
    id: 'apt-ind-106',
    clientName: 'Arjun Dasgupta',
    clientPhone: '+91 98300 44192',
    clientEmail: 'arjun.dasgupta@outlook.com',
    serviceId: 'hs-1',
    serviceName: 'Master Stylist Precision Cut & Blowdry',
    servicePrice: 750,
    stylistId: 'hs-st-2',
    stylistName: 'Rohan Kapoor',
    date: '2026-06-28',
    time: '15:00',
    status: 'completed',
    paymentStatus: 'paid_full',
    amountPaid: 750,
    createdAt: '2026-06-25T14:00:00Z',
  },
  {
    id: 'apt-ind-107',
    clientName: 'Sneha Kulkarni',
    clientPhone: '+91 99203 11840',
    clientEmail: 'sneha.kulkarni@gmail.com',
    serviceId: 'hs-3',
    serviceName: 'Signature Caramel Balayage & Olaplex Glaze',
    servicePrice: 5200,
    stylistId: 'hs-st-1',
    stylistName: 'Ananya Sharma',
    date: '2026-06-10',
    time: '10:30',
    status: 'completed',
    paymentStatus: 'paid_full',
    amountPaid: 5200,
    createdAt: '2026-06-08T09:00:00Z',
  },
  {
    id: 'apt-ind-108',
    clientName: 'Vikramaditya Roy',
    clientPhone: '+91 98190 66231',
    clientEmail: 'vikram.roy@startupindia.in',
    serviceId: 'hs-9',
    serviceName: 'Express Glow Organic Cleanup & De-Tan',
    servicePrice: 850,
    stylistId: 'hs-st-3',
    stylistName: 'Kavita Deshmukh',
    date: '2026-05-20',
    time: '17:00',
    status: 'completed',
    paymentStatus: 'paid_full',
    amountPaid: 850,
    createdAt: '2026-05-18T16:30:00Z',
  },
];

export const INITIAL_CLIENTS: ClientRecord[] = [
  {
    id: 'cli-ind-1',
    name: 'Pooja Mehra',
    phone: '+91 98451 22910',
    email: 'pooja.mehra@gmail.com',
    totalVisits: 7,
    totalSpent: 18400,
    lastVisit: '2026-08-28',
    notes: 'Regular Balayage & Keratin client. Prefers Uma for color formulations.',
    favoriteStylist: 'Uma',
    points: 1150,
    lifetimePoints: 2190,
    loyaltyTier: 'platinum',
    pointHistory: [
      { id: 'tx-1', date: '2026-08-28', description: 'Signature Caramel Balayage Visit', pointsChange: 520, type: 'spend_earned' },
      { id: 'tx-2', date: '2026-06-10', description: 'Hair Spa Rejuvenation', pointsChange: 220, type: 'spend_earned' },
      { id: 'tx-3', date: '2026-05-02', description: 'Redeemed 20% OFF Festive Voucher', pointsChange: -750, type: 'redeemed' },
      { id: 'tx-4', date: '2026-04-12', description: 'Birthday Milestone Bonus', pointsChange: 250, type: 'bonus' },
    ],
    redeemedRewards: [
      {
        id: 'red-1',
        rewardId: 'rew-3',
        rewardTitle: '20% OFF Festive & Premium Treatments',
        discountSummary: '20% OFF',
        pointsSpent: 750,
        redeemedAt: '2026-05-02',
        couponCode: 'ROYAL20-8492',
        status: 'used',
      },
    ],
  },
  {
    id: 'cli-ind-2',
    name: 'Siddharth Verma',
    phone: '+91 98201 44589',
    email: 'siddharth.verma@techcorp.in',
    totalVisits: 5,
    totalSpent: 4250,
    lastVisit: '2026-08-20',
    notes: 'Likes razor texture on crown, sharp sideburn taper.',
    favoriteStylist: 'Rohan Kapoor',
    points: 425,
    lifetimePoints: 675,
    loyaltyTier: 'silver',
    pointHistory: [
      { id: 'tx-5', date: '2026-08-20', description: 'Precision Cut & Beard Grooming', pointsChange: 125, type: 'spend_earned' },
      { id: 'tx-6', date: '2026-07-15', description: 'Visit Loyalty Bonus', pointsChange: 50, type: 'visit_earned' },
      { id: 'tx-7', date: '2026-06-01', description: 'Welcome Onboarding Bonus', pointsChange: 100, type: 'bonus' },
    ],
  },
  {
    id: 'cli-ind-3',
    name: 'Radhika Singhania',
    phone: '+91 98110 55762',
    email: 'radhika.singh@outlook.com',
    totalVisits: 4,
    totalSpent: 12200,
    lastVisit: '2026-08-15',
    notes: 'Loves Gel-X chrome designs and customized 3D nail charms by Uma.',
    favoriteStylist: 'Uma',
    points: 1220,
    lifetimePoints: 1450,
    loyaltyTier: 'gold',
    pointHistory: [
      { id: 'tx-8', date: '2026-08-15', description: 'Gel-X Extensions & Nail Art Session', pointsChange: 480, type: 'spend_earned' },
      { id: 'tx-9', date: '2026-05-18', description: 'Balayage Color & Gloss', pointsChange: 570, type: 'spend_earned' },
      { id: 'tx-10', date: '2026-03-02', description: 'First Visit Bonus', pointsChange: 150, type: 'bonus' },
    ],
  },
  {
    id: 'cli-ind-4',
    name: 'Aditya Sen',
    phone: '+91 98450 78129',
    email: 'aditya.sen@gmail.com',
    totalVisits: 2,
    totalSpent: 1250,
    lastVisit: '2026-08-30',
    notes: 'Prefers quiet sessions during haircuts.',
    favoriteStylist: 'Ananya Sharma',
    points: 175,
    lifetimePoints: 175,
    loyaltyTier: 'bronze',
    pointHistory: [
      { id: 'tx-11', date: '2026-08-30', description: 'Layered Cut & Styling', pointsChange: 95, type: 'spend_earned' },
      { id: 'tx-12', date: '2026-08-01', description: 'First Visit Welcome Points', pointsChange: 80, type: 'bonus' },
    ],
  },
  {
    id: 'cli-ind-5',
    name: 'Meera Iyer',
    phone: '+91 98860 33419',
    email: 'meera.iyer@designhouse.in',
    totalVisits: 9,
    totalSpent: 26500,
    lastVisit: '2026-08-25',
    notes: 'Bridal consultation scheduled with Uma. VIP client.',
    favoriteStylist: 'Uma',
    points: 1650,
    lifetimePoints: 3100,
    loyaltyTier: 'platinum',
    pointHistory: [
      { id: 'tx-13', date: '2026-08-25', description: 'Bridal Trial & Spa Treatment', pointsChange: 550, type: 'spend_earned' },
      { id: 'tx-14', date: '2026-07-12', description: 'Redeemed Free Deluxe Scalp Detox', pointsChange: -1200, type: 'redeemed' },
      { id: 'tx-15', date: '2026-06-05', description: 'Global Highlights & Toner', pointsChange: 650, type: 'spend_earned' },
    ],
    redeemedRewards: [
      {
        id: 'red-2',
        rewardId: 'rew-4',
        rewardTitle: 'Complimentary Scalp Detox / Hand Spa Ritual',
        discountSummary: '100% Complimentary Add-on',
        pointsSpent: 1200,
        redeemedAt: '2026-07-12',
        couponCode: 'FREESPA-4819',
        status: 'used',
      },
    ],
  },
  {
    id: 'cli-ind-6',
    name: 'Kavya Nambiar',
    phone: '+91 97412 88301',
    email: 'kavya.nambiar@gmail.com',
    totalVisits: 4,
    totalSpent: 14800,
    lastVisit: '2026-07-15', // 55 days ago
    notes: 'Keratin smoothing & hair botox specialist fan. Usually repeats keratin treatment every 8 weeks.',
    favoriteStylist: 'Uma',
    points: 880,
    lifetimePoints: 1620,
    loyaltyTier: 'gold',
    pointHistory: [
      { id: 'tx-16', date: '2026-07-15', description: 'Keratin Smoothing Session', pointsChange: 420, type: 'spend_earned' },
      { id: 'tx-17', date: '2026-05-10', description: 'Precision Cut & Conditioning', pointsChange: 150, type: 'spend_earned' },
    ],
  },
  {
    id: 'cli-ind-7',
    name: 'Arjun Dasgupta',
    phone: '+91 98300 44192',
    email: 'arjun.dasgupta@outlook.com',
    totalVisits: 3,
    totalSpent: 2250,
    lastVisit: '2026-06-28', // 72 days ago
    notes: 'Master stylist haircut client. High satisfaction with Rohan.',
    favoriteStylist: 'Rohan Kapoor',
    points: 225,
    lifetimePoints: 375,
    loyaltyTier: 'silver',
    pointHistory: [
      { id: 'tx-18', date: '2026-06-28', description: 'Master Stylist Precision Cut', pointsChange: 75, type: 'spend_earned' },
      { id: 'tx-19', date: '2026-05-15', description: 'Haircut & Styling', pointsChange: 75, type: 'spend_earned' },
    ],
  },
  {
    id: 'cli-ind-8',
    name: 'Sneha Kulkarni',
    phone: '+91 99203 11840',
    email: 'sneha.kulkarni@gmail.com',
    totalVisits: 5,
    totalSpent: 21500,
    lastVisit: '2026-06-10', // 90 days ago
    notes: 'Lapsed VIP color client. Got caramel balayage in June. Overdue for root touchup & gloss.',
    favoriteStylist: 'Ananya Sharma',
    points: 1450,
    lifetimePoints: 2450,
    loyaltyTier: 'platinum',
    pointHistory: [
      { id: 'tx-20', date: '2026-06-10', description: 'Caramel Balayage & Glaze', pointsChange: 520, type: 'spend_earned' },
      { id: 'tx-21', date: '2026-04-01', description: 'Olaplex Rebonding Spa', pointsChange: 350, type: 'spend_earned' },
    ],
  },
  {
    id: 'cli-ind-9',
    name: 'Vikramaditya Roy',
    phone: '+91 98190 66231',
    email: 'vikram.roy@startupindia.in',
    totalVisits: 2,
    totalSpent: 1700,
    lastVisit: '2026-05-20', // 111 days ago
    notes: 'Skin de-tan and express cleanup client. Booked with Kavita.',
    favoriteStylist: 'Kavita Deshmukh',
    points: 170,
    lifetimePoints: 250,
    loyaltyTier: 'bronze',
    pointHistory: [
      { id: 'tx-22', date: '2026-05-20', description: 'Express Glow Cleanup', pointsChange: 85, type: 'spend_earned' },
    ],
  },
];
