import { SocialVideo, VideoCategoryTag } from './types';

// Per-template default YouTube videos & shorts for all 14 business categories.
// Each category gets unique URLs, titles, thumbnails, tags, and channel context.

export const TEMPLATE_DEFAULT_VIDEOS: Record<string, SocialVideo[]> = {
  hair_salon: [
    { id: 'hs-v1', youtubeUrl: 'https://www.youtube.com/shorts/kJQP7kiw5Fk', videoId: 'kJQP7kiw5Fk', title: 'Balayage Dimension & Blowdry Transformation', description: 'Precision balayage with custom hair textures.', channelTitle: 'Miraki Hair Studio', thumbnailUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '48.2k views', transformationTag: 'Color & Cut' },
    { id: 'hs-v2', youtubeUrl: 'https://www.youtube.com/shorts/fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'Structural Bob & Layer Reveal', description: 'Geometric dry cut with texturized layers.', channelTitle: 'Miraki Hair Studio', thumbnailUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '32.1k views', transformationTag: 'Precision Cut' },
    { id: 'hs-v3', youtubeUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'Master Balayage & High-Gloss Hair Transformation', description: 'Full hair transformation with bond-building treatment.', channelTitle: 'Miraki Hair Studio', thumbnailUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHOWCASE', isOwnerVideo: false, views: '12.4k views', transformationTag: 'Hair Transformation' },
  ],
  barber: [
    { id: 'bb-v1', youtubeUrl: 'https://www.youtube.com/shorts/3JZ_D3ELwOQ', videoId: '3JZ_D3ELwOQ', title: 'Straight Razor Hot Towel Shave Reel', description: 'Classic straight razor shave with hot towel ritual.', channelTitle: 'The Royal Blade', thumbnailUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '28.1k views', transformationTag: 'Traditional Shave' },
    { id: 'bb-v2', youtubeUrl: 'https://www.youtube.com/shorts/tgbNymZ7vqY', videoId: 'tgbNymZ7vqY', title: 'Skin Fade & Beard Sculpting Reel', description: 'Sharp skin fade with sculpted beard architecture.', channelTitle: 'The Royal Blade', thumbnailUrl: 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '54.9k views', transformationTag: 'Beard Craft' },
  ],
  unisex_salon: [
    { id: 'us-v1', youtubeUrl: 'https://www.youtube.com/shorts/pAgnJDJN4VA', videoId: 'pAgnJDJN4VA', title: 'Modern Minimalist Studio Interior', description: 'Contemporary unisex salon with private suites.', channelTitle: 'Aura Unisex Salon', thumbnailUrl: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '29.3k views', transformationTag: 'Interior' },
    { id: 'us-v2', youtubeUrl: 'https://www.youtube.com/shorts/fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'Couple Makeover Weekend Package', description: 'Couple treatment suite with hair and skin rituals.', channelTitle: 'Aura Unisex Salon', thumbnailUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '32.1k views', transformationTag: 'Couple Rituals' },
  ],
  beauty_parlour: [
    { id: 'bp-v1', youtubeUrl: 'https://www.youtube.com/shorts/3JZ_D3ELwOQ', videoId: '3JZ_D3ELwOQ', title: 'Herbal Facial & Threading Artistry', description: 'Organic facial with traditional threading artistry.', channelTitle: 'Roop Mahal', thumbnailUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '61.0k views', transformationTag: 'Facial Glow' },
    { id: 'bp-v2', youtubeUrl: 'https://www.youtube.com/watch?v=L_LUpnjgPso', videoId: 'L_LUpnjgPso', title: 'Bridal Pre-Glow Herbal Body Polish', description: 'Pre-bridal herbal body polish and golden sheen therapy.', channelTitle: 'Roop Mahal', thumbnailUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=80', categoryTag: 'LONG', isOwnerVideo: false, views: '19.8k views', transformationTag: 'Skin Care' },
  ],
  nail_studio: [
    { id: 'ns-v1', youtubeUrl: 'https://www.youtube.com/shorts/kJQP7kiw5Fk', videoId: 'kJQP7kiw5Fk', title: 'Chrome Aura Nail Set', description: 'High-shine chrome gel art with aura design.', channelTitle: 'Pinky Nails Studio', thumbnailUrl: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '48.2k views', transformationTag: '3D Aura Nail Art' },
    { id: 'ns-v2', youtubeUrl: 'https://www.youtube.com/shorts/fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'Russian Cuticle Precision Manicure', description: 'Russian dry e-file cuticle technique with diamond bits.', channelTitle: 'Pinky Nails Studio', thumbnailUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '32.1k views', transformationTag: 'Cuticle Care' },
  ],
  hair_spa: [
    { id: 'hsp-v1', youtubeUrl: 'https://www.youtube.com/shorts/3JZ_D3ELwOQ', videoId: '3JZ_D3ELwOQ', title: 'Japanese Ozone Mist Scalp Detox', description: 'Micro-camera follicle diagnosis and herbal detox.', channelTitle: 'Kesh Prakriti Hair Spa', thumbnailUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '61.0k views', transformationTag: 'Scalp Detox' },
    { id: 'hsp-v2', youtubeUrl: 'https://www.youtube.com/watch?v=L_LUpnjgPso', videoId: 'L_LUpnjgPso', title: 'Trichology Wellness Ritual', description: 'Deep scalp therapy with ozone mist and botanical oils.', channelTitle: 'Kesh Prakriti Hair Spa', thumbnailUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=600&q=80', categoryTag: 'LONG', isOwnerVideo: false, views: '19.8k views', transformationTag: 'Hair Spa' },
  ],
  skincare_clinic: [
    { id: 'sc-v1', youtubeUrl: 'https://www.youtube.com/shorts/pAgnJDJN4VA', videoId: 'pAgnJDJN4VA', title: 'Medical Hydra-Facial Suite Tour', description: 'Clinical hydra-dermabrasion and LED light therapy.', channelTitle: 'Dermacure Clinic', thumbnailUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '29.3k views', transformationTag: 'Hydration' },
    { id: 'sc-v2', youtubeUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'Glass Skin Clinical Transformation', description: 'Medical-grade peel, hydration and radiance protocol.', channelTitle: 'Dermacure Clinic', thumbnailUrl: 'https://images.unsplash.com/photo-1512290900672-1f55b9e07506?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHOWCASE', isOwnerVideo: false, views: '12.4k views', transformationTag: 'Skin Care' },
  ],
  makeup_studio: [
    { id: 'ms-v1', youtubeUrl: 'https://www.youtube.com/shorts/fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'HD Airbrush Bridal Glam Reel', description: 'Flawless 4K airbrush bridal makeup with glass skin finish.', channelTitle: 'Vogue Noir Makeup Studio', thumbnailUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '32.1k views', transformationTag: 'Bridal' },
    { id: 'ms-v2', youtubeUrl: 'https://www.youtube.com/shorts/kJQP7kiw5Fk', videoId: 'kJQP7kiw5Fk', title: 'Red Carpet Cocktail Glow', description: 'Golden hour strobing with shimmer eyes and smudge-proof lips.', channelTitle: 'Vogue Noir Makeup Studio', thumbnailUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '48.2k views', transformationTag: 'Evening Glam' },
  ],
  massage_wellness: [
    { id: 'mw-v1', youtubeUrl: 'https://www.youtube.com/shorts/3JZ_D3ELwOQ', videoId: '3JZ_D3ELwOQ', title: 'Volcanic Hot Stone Therapy Reel', description: 'Warm pink crystal stones infused with 84 minerals.', channelTitle: 'Bodhi Tree Wellness', thumbnailUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '61.0k views', transformationTag: 'Hot Stone' },
    { id: 'mw-v2', youtubeUrl: 'https://www.youtube.com/shorts/tgbNymZ7vqY', videoId: 'tgbNymZ7vqY', title: 'Deep Tissue Muscle Knot Release', description: 'Firm pressure strokes targeting chronic tension.', channelTitle: 'Bodhi Tree Wellness', thumbnailUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '54.9k views', transformationTag: 'Deep Tissue' },
  ],
  hair_coloring: [
    { id: 'hc-v1', youtubeUrl: 'https://www.youtube.com/shorts/fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'Caramel Balayage & Olaplex Glaze', description: 'Custom hand-painted caramel highlights with bond repair.', channelTitle: 'Prism & Chroma', thumbnailUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '32.1k views', transformationTag: 'Balayage' },
    { id: 'hc-v2', youtubeUrl: 'https://www.youtube.com/shorts/3JZ_D3ELwOQ', videoId: '3JZ_D3ELwOQ', title: 'Ash Blonde Platinum Lift', description: 'Level 10 lift with brass-canceling toner.', channelTitle: 'Prism & Chroma', thumbnailUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '61.0k views', transformationTag: 'Lightening' },
  ],
  bridal_lounge: [
    { id: 'bl-v1', youtubeUrl: 'https://www.youtube.com/shorts/kJQP7kiw5Fk', videoId: 'kJQP7kiw5Fk', title: 'Royal Rajasthani Bridal Glow', description: 'Full bridal HD makeup with heirloom jewelry placement.', channelTitle: 'Shringaar Lounge', thumbnailUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '48.2k views', transformationTag: 'Bridal Makeover' },
    { id: 'bl-v2', youtubeUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'Destination Bride Sunset Portrait', description: 'Luxury bridal makeover and sunset bridal shoot.', channelTitle: 'Shringaar Lounge', thumbnailUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80', categoryTag: 'LONG', isOwnerVideo: false, views: '12.4k views', transformationTag: 'Destination' },
  ],
  tattoo_studio: [
    { id: 'ts-v1', youtubeUrl: 'https://www.youtube.com/shorts/3JZ_D3ELwOQ', videoId: '3JZ_D3ELwOQ', title: 'Fine-Line Sacred Geometry Tattoo', description: 'Single-needle precise geometric art.', channelTitle: 'Iron & Ink', thumbnailUrl: 'https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '61.0k views', transformationTag: 'Fine Line' },
    { id: 'ts-v2', youtubeUrl: 'https://www.youtube.com/shorts/fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'Micro-Realism Pet Portrait Reel', description: 'Photo-realistic fine-line portrait art.', channelTitle: 'Iron & Ink', thumbnailUrl: 'https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '32.1k views', transformationTag: 'Custom Sleeve' },
  ],
  lash_brow: [
    { id: 'lb-v1', youtubeUrl: 'https://www.youtube.com/shorts/kJQP7kiw5Fk', videoId: 'kJQP7kiw5Fk', title: 'Russian Volume Lash Extensions', description: 'Handmade cashmere fans for intense volume.', channelTitle: 'Arch & Flutter', thumbnailUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '48.2k views', transformationTag: 'Lashes' },
    { id: 'lb-v2', youtubeUrl: 'https://www.youtube.com/shorts/fJ9rUzIMcZQ', videoId: 'fJ9rUzIMcZQ', title: 'Feather Microblading Reveal', description: 'Golden ratio mapped hair strokes for brows.', channelTitle: 'Arch & Flutter', thumbnailUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: false, views: '32.1k views', transformationTag: 'Microblading' },
  ],
  ayurvedic_spa: [
    { id: 'ay-v1', youtubeUrl: 'https://www.youtube.com/shorts/3JZ_D3ELwOQ', videoId: '3JZ_D3ELwOQ', title: 'Shirodhara Medicated Oil Stream', description: 'Continuous warm herbal oil stream on the third eye.', channelTitle: 'Veda Sanjeevani', thumbnailUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80', categoryTag: 'SHORT', isOwnerVideo: true, views: '61.0k views', transformationTag: 'Shirodhara' },
    { id: 'ay-v2', youtubeUrl: 'https://www.youtube.com/watch?v=L_LUpnjgPso', videoId: 'L_LUpnjgPso', title: '4-Hand Abhyangam Full Body Therapy', description: 'Synchronized traditional oil massage with herbal elixirs.', channelTitle: 'Veda Sanjeevani', thumbnailUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80', categoryTag: 'LONG', isOwnerVideo: false, views: '19.8k views', transformationTag: 'Abhyangam' },
  ]
};

export function getDefaultVideosForTemplate(categoryId?: string): SocialVideo[] {
  if (!categoryId) return [];
  return TEMPLATE_DEFAULT_VIDEOS[categoryId] || [];
}
